export const DATA = [
  {
    id: 1,
    title: 'Casas',
    name: 'Hermosa Casa Tipo Chalet, Luminosa, En El Exclusivo Barrio Residencial Arrayanes De El Bolsón',
    carouselName: 'CASA TIPO CHALET Barrio Arrayanes, El Bolsón',
    province: 'Río Negro',
    location: 'El Bolsón',
    address: 'Los Arrayanes 4753, Arrayanes, El Bolsón, Río Negro',
    locationX: '-71.52935',
    locationY: '-41.94503',
    imageUrl: 'https://347inmobiliaria.com/img/1/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/1/1.jpg',
      'https://347inmobiliaria.com/img/1/2.jpg',
      'https://347inmobiliaria.com/img/1/3.jpg',
      'https://347inmobiliaria.com/img/1/4.jpg',
      'https://347inmobiliaria.com/img/1/5.jpg',
      'https://347inmobiliaria.com/img/1/6.jpg',
      'https://347inmobiliaria.com/img/1/7.jpg',
      'https://347inmobiliaria.com/img/1/8.jpg',
      'https://347inmobiliaria.com/img/1/9.jpg',
      'https://347inmobiliaria.com/img/1/10.jpg',
      'https://347inmobiliaria.com/img/1/11.jpg',
      'https://347inmobiliaria.com/img/1/12.jpg',
      'https://347inmobiliaria.com/img/1/13.jpg',
      'https://347inmobiliaria.com/img/1/14.jpg',
      'https://347inmobiliaria.com/img/1/15.jpg',
      'https://347inmobiliaria.com/img/1/16.jpg',
      'https://347inmobiliaria.com/img/1/17.jpg',
      'https://347inmobiliaria.com/img/1/18.jpg',
    ],
    description: 'Comedor, Living, Jardín, Cocina, Lavadero, TV por cable, Línea telefónica, Gas natural, Placards.\n Venir a vivir a un zona tranquila, rodeada de naturaleza y buena gente. Casa de construcción de calidad con material, de arquitectura espontanea, con terreno de 475 m². Muy Buena ubicación residencial, con loza radiante en todos los ambientes haciendo que el dia a dia sea más calido un bello jardin de suelo plano. Plaza de juegos creca. Todos los servicios. A 7 cuadras del centro de Bolsón.',
    price: 'USD 120.000',
    size: '475',
    build: '87.5',
    cover: '61',
    rooms: '3',
    bedrooms: '2',
    bathroom: '1',
    storage: '',
    garage: '1',
    floors: '1',
    orientation: 'norte',
    antiquity: '20 años',
  },
  {
    id: 2,
    title: 'Departamentos',
    name: 'Excelente Ubicacion Departamento Martinez, zona Norte, Buenos Aires',
    carouselName: 'Excelente Ubicacion Departamento Martinez, zona Norte, Buenos Aires',
    province: 'Buenos Aires',
    location: 'Martínez',
    address: 'Juan José Paso 409, Martínez, Buenos Aires',
    locationX: '-58.4973653',
    locationY: '-34.4892018',
    imageUrl: 'https://347inmobiliaria.com/img/2/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/2/1.jpg',
      'https://347inmobiliaria.com/img/2/2.jpg',
      'https://347inmobiliaria.com/img/2/3.jpeg',
      'https://347inmobiliaria.com/img/2/4.jpeg',
      'https://347inmobiliaria.com/img/2/5.jpeg',
      'https://347inmobiliaria.com/img/2/6.jpeg',
      'https://347inmobiliaria.com/img/2/7.jpeg',
      'https://347inmobiliaria.com/img/2/8.jpeg',
    ],
    description: '',
    price: 'USD 120.000',
    expenses: '$7000',
    size: '47.23',
    build: '47.23',
    cover: '47.23',
    rooms: '3',
    bedrooms: '2',
    bathroom: '1',
    garage: '',
    apartmentsPerFloor: '4',
    arranged: 'frente',
    orientation: 'norte',
    antiquity: '38 años',
  },
  {
    id: 3,
    title: 'Chacras',
    name: 'Chacra Con Casa Y Camping A Estrenar En Zona Paradisíaca, Terminaciones De Excelente Calidad. Con Opción Alquiler!!!. Vive La Experiencia!!',
    carouselName: 'CHACRA frente a costa de Río Azul con camping de categoría, zona paradisíaca',
    province: 'Río Negro',
    location: 'El Bolsón',
    address: 'A orillas del Rio azul, en El Bolsón',
    locationX: '-71.56202435473318',
    locationY: '-41.934127379336054',
    imageUrl: 'https://347inmobiliaria.com/img/3/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/3/1.jpg',
      'https://347inmobiliaria.com/img/3/2.jpg',
      'https://347inmobiliaria.com/img/3/3.jpg',
      'https://347inmobiliaria.com/img/3/4.jpg',
      'https://347inmobiliaria.com/img/3/5.jpg',
      'https://347inmobiliaria.com/img/3/6.jpg',
      'https://347inmobiliaria.com/img/3/7.jpg',
      'https://347inmobiliaria.com/img/3/8.jpg',
      'https://347inmobiliaria.com/img/3/9.jpg',
      'https://347inmobiliaria.com/img/3/10.jpg',
      'https://347inmobiliaria.com/img/3/11.jpg',
      'https://347inmobiliaria.com/img/3/12.jpg',
      'https://347inmobiliaria.com/img/3/13.jpg',
      'https://347inmobiliaria.com/img/3/14.jpg',
      'https://347inmobiliaria.com/img/3/15.jpg',
      'https://347inmobiliaria.com/img/3/16.jpg',
      'https://347inmobiliaria.com/img/3/17.jpg',
      'https://347inmobiliaria.com/img/3/18.jpg',
      'https://347inmobiliaria.com/img/3/19.jpg',
      'https://347inmobiliaria.com/img/3/20.jpg',
      'https://347inmobiliaria.com/img/3/21.jpg',
      'https://347inmobiliaria.com/img/3/22.jpg',
      'https://347inmobiliaria.com/img/3/23.jpg',
      'https://347inmobiliaria.com/img/3/24.jpg',
      'https://347inmobiliaria.com/img/3/25.jpg',
      'https://347inmobiliaria.com/img/3/26.jpg',
    ],
    description: 'Vivir en un lugar soñado, tranquilo y disfrutar de la naturaleza!!! *Chacra de 1 Hra. rodeada de Reserva Natural sobre la costa del río Azul. Tiene árboles nativos de cientos de años, árboles frutales. **CASA: Planos aprobados por la Municipalidad. Superficie cubierta 160 m² + superficie Semi cubierta 90 m². Construcción mixta material ladrillos de adobe y arena volcánica, revestida de sidding, doble vidrio termopanel, estufa Gymse de alto rendimiento. Comedor, Living, Patio, Cocina, Dependencia de servicio, Playroom, Lavadero, 1 baño, 1 habitación. Deck. Instalaciones para un segundo baño. Leñero y cochera. Muy luminosa. Posible Hostel. **CAMPING: con habilitación comercial y perfil de Google My business muy bien posicionado. Superficie cubierta 68,92 m2 + superficie Semi cubierta 11,89 m². Consta de 3 dormis canadienses de 12 m² c/u. area de acampe con Luz, agua, parrillas, mesas, asientos y fogones, 2 baños, 4 duchas, cocina comunitaria horno de barro, cocina industrial con horno, heladera y frizer. *Extras: Electricidad. Equipo de paneles solares de 3000 Kwa. pozo de agua potable. termo-tanque solar y a gas.',
    price: 'USD 380.000',
    size: '10000',
    build: '250',
    cover: '160',
    rooms: '3',
    bedrooms: '1',
    bathroom: '1',
    storage: '1',
    garage: '2',
    access: 'ripio',
    distanceToAsphalt: '1 km',
    orientation: 'norte',
    antiquity: '2 años',
  },
  {
    id: 4,
    title: 'Depósitos',
    name: 'Gran deposito de uso industrial con dos oficinas independientes, amplio terreno, en Cerro Radal, Parque Industrial, Lago Puelo, Chubut',
    carouselName: 'Gran depósito de uso industrial, en Cerro Radal, Parque industrial, Lago Puelo',
    province: 'Chubut',
    location: 'Lago Puelo',
    address: 'A 2 cuadras de la ruta 45 de Radal, a 6 km de Lago Puelo y 10 de El Bolsón',
    locationX: '-71.57038078244263',
    locationY: '-42.03140295981902',
    imageUrl: 'https://347inmobiliaria.com/img/4/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/4/1.jpg',
      'https://347inmobiliaria.com/img/4/2.jpg',
      'https://347inmobiliaria.com/img/4/3.jpg',
      'https://347inmobiliaria.com/img/4/4.jpg',
      'https://347inmobiliaria.com/img/4/5.jpg',
      'https://347inmobiliaria.com/img/4/6.jpg',
      'https://347inmobiliaria.com/img/4/7.jpg',
      'https://347inmobiliaria.com/img/4/8.jpg',
      'https://347inmobiliaria.com/img/4/9.jpg',
      'https://347inmobiliaria.com/img/4/10.jpg',
      'https://347inmobiliaria.com/img/4/11.jpg',
      'https://347inmobiliaria.com/img/4/12.jpg',
      'https://347inmobiliaria.com/img/4/13.jpg',
      'https://347inmobiliaria.com/img/4/14.jpg',
      'https://347inmobiliaria.com/img/4/15.jpg',
      'https://347inmobiliaria.com/img/4/16.jpg',
      'https://347inmobiliaria.com/img/4/17.jpg',
      'https://347inmobiliaria.com/img/4/18.jpg',
      'https://347inmobiliaria.com/img/4/19.jpg',
      'https://347inmobiliaria.com/img/4/20.jpg',
      'https://347inmobiliaria.com/img/4/21.jpg',
      'https://347inmobiliaria.com/img/4/22.jpg',
    ],
    description: '*Galpon/Deposito de 285 m². *casa/oficina de 117,50 m²con baño completo. *oficina/vestuario de 58 m² con baño completo. Buena ubicación zona industrial/comercial. Amplio terreno, Pozo de agua para riego. Instalación de electricidad trifásica. Todos los servicios',
    price: 'USD 220.000',
    size: '3180',
    build: '285',
    cover: '260',
    rooms: '',
    bedrooms: '',
    bathroom: '1',
    storage: '',
    offices: '2',
    height: '6.5 m',
    garage: '2',
    access: '',
    floorSupport: '20 t/m²',
    distanceToAsphalt: '',
    orientation: '',
    antiquity: '8 años',
  },
  {
    id: 5,
    title: 'Casas',
    name: 'Casa Nueva!!!! Muy Luminosa, Varios Ambientes. En Alto Di Puelo, Destino Turístico Por Excelencia. Lago Puelo, Chubut',
    carouselName: 'En venta, Casa nueva!! Muy luminosa, varios ambientes. En Alto Di Puelo, destino turístico por excelencia',
    province: 'Chubut',
    location: 'Lago Puelo',
    address: 'A 1 km del centro de Lago Puelo',
    locationX: '-71.5871262',
    locationY: '-42.0348125',
    imageUrl: 'https://347inmobiliaria.com/img/5/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/5/1.jpg',
      'https://347inmobiliaria.com/img/5/2.jpg',
      'https://347inmobiliaria.com/img/5/3.jpg',
      'https://347inmobiliaria.com/img/5/4.jpg',
      'https://347inmobiliaria.com/img/5/5.jpg',
      'https://347inmobiliaria.com/img/5/6.jpg',
      'https://347inmobiliaria.com/img/5/7.jpg',
      'https://347inmobiliaria.com/img/5/8.jpg',
      'https://347inmobiliaria.com/img/5/9.jpg',
      'https://347inmobiliaria.com/img/5/10.jpg',
      'https://347inmobiliaria.com/img/5/11.jpg',
      'https://347inmobiliaria.com/img/5/12.jpg',
      'https://347inmobiliaria.com/img/5/13.jpg',
      'https://347inmobiliaria.com/img/5/14.jpg',
      'https://347inmobiliaria.com/img/5/15.jpg',
      'https://347inmobiliaria.com/img/5/16.jpg',
      'https://347inmobiliaria.com/img/5/17.jpg',
      'https://347inmobiliaria.com/img/5/18.jpg',
      'https://347inmobiliaria.com/img/5/19.jpg',
      'https://347inmobiliaria.com/img/5/20.jpg',
      'https://347inmobiliaria.com/img/5/21.jpg',
      'https://347inmobiliaria.com/img/5/22.jpg',
      'https://347inmobiliaria.com/img/5/23.jpg',
      'https://347inmobiliaria.com/img/5/24.jpg',
      'https://347inmobiliaria.com/img/5/25.jpg',
      'https://347inmobiliaria.com/img/5/26.jpg',
      'https://347inmobiliaria.com/img/5/27.jpg',
      'https://347inmobiliaria.com/img/5/28.jpg',
      'https://347inmobiliaria.com/img/5/29.jpg',
      'https://347inmobiliaria.com/img/5/30.jpg',
      'https://347inmobiliaria.com/img/5/31.jpg',
      'https://347inmobiliaria.com/img/5/32.jpg',
      'https://347inmobiliaria.com/img/5/33.jpg',
      'https://347inmobiliaria.com/img/5/34.jpg',
      'https://347inmobiliaria.com/img/5/35.jpg',
    ],
    description: 'Hermosa casa con amplias ventanas, gran living comedor con estufa a leña en el centro, muy calentita en invierno, toda la casa cuenta con doble vidrio. Gran jardín al rededor de la casa, con árbol frutal de ciruelas. con preciosa vista hacia la montaña copada de árboles autóctonos, fácil acceso al barrio por camino de azfalto alternativo de la ruta 16',
    price: 'USD 180.000',
    size: '908',
    build: '135',
    cover: '95',
    rooms: '4',
    bedrooms: '3',
    bathroom: '2',
    garage: '1',
    storage: '',
    floors: '2',
    orientation: 'Oeste',
    antiquity: '2 años',
  },
  {
    id: 6,
    title: 'Casas',
    name: 'Mudarte A La Patagonia Es Posible!! Una Casa Para Vivir Y Otra para La Renta en la exclusiva zona Villa Del Lago, Lago Puelo, Chubut',
    carouselName: 'DOS CASAS en un lote camino al parque nacional Lago Puelo',
    province: 'Chubut',
    location: 'Lago Puelo',
    address: 'Callejón el tero, a dos cuadras de la ruta 16, Villa del lago, Lago Puelo',
    locationX: '-71.606781',
    locationY: '-42.082462',
    imageUrl: 'https://347inmobiliaria.com/img/6/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/6/1.jpg',
      'https://347inmobiliaria.com/img/6/2.jpg',
      'https://347inmobiliaria.com/img/6/3.jpg',
      'https://347inmobiliaria.com/img/6/4.jpg',
      'https://347inmobiliaria.com/img/6/5.jpg',
      'https://347inmobiliaria.com/img/6/6.jpg',
      'https://347inmobiliaria.com/img/6/7.jpg',
      'https://347inmobiliaria.com/img/6/8.jpg',
      'https://347inmobiliaria.com/img/6/9.jpg',
      'https://347inmobiliaria.com/img/6/10.jpg',
      'https://347inmobiliaria.com/img/6/11.jpg',
      'https://347inmobiliaria.com/img/6/12.jpg',
      'https://347inmobiliaria.com/img/6/13.jpg',
      'https://347inmobiliaria.com/img/6/14.jpg',
      'https://347inmobiliaria.com/img/6/15.jpg',
      'https://347inmobiliaria.com/img/6/16.jpg',
      'https://347inmobiliaria.com/img/6/17.jpg',
      'https://347inmobiliaria.com/img/6/18.jpg',
      'https://347inmobiliaria.com/img/6/19.jpg',
      'https://347inmobiliaria.com/img/6/20.jpg',
      'https://347inmobiliaria.com/img/6/21.jpg',
      'https://347inmobiliaria.com/img/6/22.jpg',
      'https://347inmobiliaria.com/img/6/23.jpg',
      'https://347inmobiliaria.com/img/6/24.jpg',
      'https://347inmobiliaria.com/img/6/25.jpg',
    ],
    description: '*Ambientes: Comedor, Estudio, Living, Patio, Jardín, Cocina, Dependencia de servicio, Playroom, Lavadero. *Comodidades y equipamiento: Comedor, Estudio, Living, Patio, Jardín, Cocina, Dependencia de servicio, Playroom. *Características adicionales: Acceso a internet, Parrilla. -Terreno 714 m2 En una zona exclusiva, camino al lago de Lago Puelo. Hoy en día considerado boom turístico de la Patagonia. Son dos casas de construcción rústicas construidas por sus mismos dueños, con la elección y dedicación que eso implica. -Venden por viaje. -Ubicación callejón el tero, villa del lago, Lago Puelo, chubut. Calle de ripio, a dos cuadras de la ruta 16 (azfalto). -2 casas: Una para vivir y otra para renta; o compartir en familia. +Primer casa: 58,68 m². superficie cubierta + 12 m² semi cubierta. 10 años de antigüedad. Da hacia la calle con jardín en la entrada. consta de dos plantas; living, cocina, comedor, con habitación en planta baja y baño completo. Posibilidad de ampliación. Planta alta de dos habitaciones y sala de estar o play room. Muy luminosa. (hoy alquilada, con muy buenos inquilinos). Ancho de puertas amplias y agarradera en la ducha, como para considerar situación de silla de ruedas y/o gente mayor o con dificultad de traslado. +Segunda casa: de una sola planta, de 35,5 m² superficie cubierta + 12 m² semi cubierta, 20 años de antigüedad; 2 habitaciones, Cocina/comedor, baño, lavadero, pequeño taller y patio con alero. cuenta con gran jardín en la parte trasera de la casa. Todos los servicios, teléfono fijo, electricidad, gas natural. Amplio jardín con enorme cerezo y flores. Parrilla. Pozo de agua para riego, dos tanques de reserva de agua. Ambas casas con cocheras con entrada independiente y techadas. *Aceptan camioneta en parte de pago.',
    price: 'USD 150.000',
    size: '714',
    build: '70.68',
    cover: '58.68',
    rooms: '5',
    bedrooms: '3',
    bathroom: '1',
    garage: '2',
    storage: '2',
    floors: '2',
    orientation: 'Oeste',
    antiquity: '10 años',
  },
  {
    id: 7,
    title: 'Casas',
    name: 'Casa 2 Dormitorios, Con 2,300 M² De Terrreno, En Cerro Amigo Cerca Al Mirador De El Bolsón, Amplio Jardín',
    carouselName: 'Preciosa CHACRA en la ladera del cerro de la Cruz, de 2.300 m² de terreno',
    province: 'Río Negro',
    location: 'El Bolsón',
    address: 'Subida Del Bosque 3634, R8430, El Bolsón, Río Negro',
    locationX: '-71.5214527',
    locationY: '-41.9572917',
    imageUrl: 'https://347inmobiliaria.com/img/7/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/7/1.jpg',
      'https://347inmobiliaria.com/img/7/2.jpg',
      'https://347inmobiliaria.com/img/7/3.jpg',
      'https://347inmobiliaria.com/img/7/4.jpg',
      'https://347inmobiliaria.com/img/7/5.jpg',
      'https://347inmobiliaria.com/img/7/6.jpg',
      'https://347inmobiliaria.com/img/7/7.jpg',
      'https://347inmobiliaria.com/img/7/8.jpg',
      'https://347inmobiliaria.com/img/7/9.jpg',
      'https://347inmobiliaria.com/img/7/10.jpg',
      'https://347inmobiliaria.com/img/7/11.jpg',
      'https://347inmobiliaria.com/img/7/12.jpg',
      'https://347inmobiliaria.com/img/7/13.jpg',
      'https://347inmobiliaria.com/img/7/14.jpg',
      'https://347inmobiliaria.com/img/7/15.jpg',
      'https://347inmobiliaria.com/img/7/16.jpg',
      'https://347inmobiliaria.com/img/7/17.jpg',
      'https://347inmobiliaria.com/img/7/18.jpg',
      'https://347inmobiliaria.com/img/7/19.jpg',
      'https://347inmobiliaria.com/img/7/20.jpg',
      'https://347inmobiliaria.com/img/7/21.jpg',
      'https://347inmobiliaria.com/img/7/22.jpg',
      'https://347inmobiliaria.com/img/7/23.jpg',
      'https://347inmobiliaria.com/img/7/24.jpg',
    ],
    description: '*Ambientes, Comodidades y equipamiento: Comedor, Living, Cocina, Lavadero, Jardín. *Características adicionales: *Condiciones especiales. Casa de amplios ambientes con precioso jardín, Tanque de agua. ´Arboles frutales, tierra cultivable en terrazas. Una vida de ensueño, vivir en alto, en una zona tranquila, con la naturaleza, rodeada de árboles autóctonos y montañas, a pocos metros del Mirador de El Bolsón, una caminata preciosa de árboles que dan gran frescor en verano y al final te encuentras con una vista panorámica del valle y sus alrededores. La casa se encuentra a tan solo 10 minutos del centro de El Bolsón, zona turística por excelencia.',
    price: 'USD 120.000',
    size: '2300',
    build: '65.59',
    cover: '65.59',
    rooms: '3',
    bedrooms: '2',
    bathroom: '1',
    garage: '1',
    storage: '',
    floors: '2',
    orientation: 'Oeste',
    antiquity: '10 años',
  },
  {
    id: 8,
    title: 'Casas',
    name: 'Casa Nueva, Una Sola Planta, En Barrio Residencial De Lago Puelo, Cerca Al Rio Azul',
    carouselName: 'CASA en una planta, Isla Norte, Lago Puelo',
    province: 'Chubut',
    location: 'Lago Puelo',
    address: 'Laguna Espejo, Lago Puelo, cerca al Rio Azul',
    locationX: '-71.60929980064807',
    locationY: '-42.05207150543498',
    imageUrl: 'https://347inmobiliaria.com/img/8/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/8/1.jpg',
      'https://347inmobiliaria.com/img/8/2.jpg',
      'https://347inmobiliaria.com/img/8/3.jpg',
      'https://347inmobiliaria.com/img/8/4.jpg',
      'https://347inmobiliaria.com/img/8/5.jpg',
      'https://347inmobiliaria.com/img/8/6.jpg',
      'https://347inmobiliaria.com/img/8/7.jpg',
      'https://347inmobiliaria.com/img/8/8.jpg',
      'https://347inmobiliaria.com/img/8/9.jpg',
      'https://347inmobiliaria.com/img/8/10.jpg',
      'https://347inmobiliaria.com/img/8/11.jpg',
      'https://347inmobiliaria.com/img/8/12.jpg',
      'https://347inmobiliaria.com/img/8/13.jpg',
    ],
    description: '*Casa de amplios ambientes de área social. Agradable distribución con doble entrada, principal y de servicio. Muy Luminosa, en una sola planta de 3 dormitorios (uno en suite), 2 baños completos con bañera, cuenta con altillo para guardar cosas. Gran Jardín en Terreno de 600 m², algunos frutales y cuenta con hermosa vista hacia el Cerro Motoco y sus cascadas, hermoso atractivo turístico de Lago Puelo. Tiene Pozo de agua para riego. -Todos los servicios: agua corriente, luz, gas natural, internet. Es un barrio tranquilo, silencioso, calle de ripio. -Se acepta permuta como parte de pago',
    price: 'USD 120.000',
    size: '100',
    build: '100',
    cover: '100',
    rooms: '4',
    bedrooms: '3',
    bathroom: '2',
    garage: '',
    storage: '1',
    floors: '1',
    orientation: 'Este',
    antiquity: '3 años',
  },
  {
    id: 9,
    title: 'Depósitos',
    name: 'Excelente Y Amplio Depósito Zona Industrial y Comercial En Esquina, 2.838,66 M2 De Terreno Sobre Ruta 45, Parque Industrial, Cerro Radal, Lago Puelo, Zona Comercial',
    carouselName: 'DEPOSITO en esquina sobre la ruta!! Parque industrial Radal, Lago Puelo',
    province: 'Chubut',
    location: 'Lago Puelo',
    address: 'Ruta 45, Parque Industrial, Cerro Radal, Lago Puelo',
    locationX: '-71.56791315006849',
    locationY: '-42.031673910101844',
    imageUrl: 'https://347inmobiliaria.com/img/9/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/9/1.jpg',
      'https://347inmobiliaria.com/img/9/2.jpg',
      'https://347inmobiliaria.com/img/9/3.jpg',
      'https://347inmobiliaria.com/img/9/4.jpg',
      'https://347inmobiliaria.com/img/9/5.jpg',
      'https://347inmobiliaria.com/img/9/6.jpg',
      'https://347inmobiliaria.com/img/9/7.jpg',
      'https://347inmobiliaria.com/img/9/8.jpg',
      'https://347inmobiliaria.com/img/9/9.jpg',
      'https://347inmobiliaria.com/img/9/10.jpg',
      'https://347inmobiliaria.com/img/9/11.jpg',
      'https://347inmobiliaria.com/img/9/12.jpg',
      'https://347inmobiliaria.com/img/9/13.jpg',
      'https://347inmobiliaria.com/img/9/14.jpg',
      'https://347inmobiliaria.com/img/9/15.jpg',
      'https://347inmobiliaria.com/img/9/16.jpg',
      'https://347inmobiliaria.com/img/9/17.jpg',
      'https://347inmobiliaria.com/img/9/18.jpg',
      'https://347inmobiliaria.com/img/9/19.jpg',
      'https://347inmobiliaria.com/img/9/20.jpg',
      'https://347inmobiliaria.com/img/9/21.jpg',
      'https://347inmobiliaria.com/img/9/22.jpg',
      'https://347inmobiliaria.com/img/9/23.jpg',
      'https://347inmobiliaria.com/img/9/24.jpg',
      'https://347inmobiliaria.com/img/9/25.jpg',
      'https://347inmobiliaria.com/img/9/26.jpg',
      'https://347inmobiliaria.com/img/9/27.jpg',
      'https://347inmobiliaria.com/img/9/28.jpg',
    ],
    description: 'Gran depósito o nave industrial en esquina, inmejorable ubicación, en zona industrial de Lago Puelo, lugar de exponencial crecimiento turístico. \n*Terreno de 2.838,66 m2. \n*Maestranza o deposito de aproximadamente 450 m². \n*Dos oficinas tres baños. \n*Oficina 1, de 48,96 m², 2 ambientes, ubicada al lado de la maestranza, tiene baño completo, cocina, con entrada compartida y entrada independiente desde la calle. \n*Oficina 2, de 46 m², y un entre piso de 23, 40 m², ubicado en la parte de atrás del galpon, con cocina, baño completo, paredes recubiertas de madera, con estufa a gas y a leña, entrada independiente desde el jardín. \n*deposito aproximadamente 25 m². Instalación eléctrica trifásica fácil acceso para automóviles y camiones, en esquina sobre ruta de asfalto. pequeño centro comercial a 2 km., escuela a una cuadra. \nUbicación del Galpon muy cercano al centro de Lago Puelo 5 km. y de El Bolson 8 km. Esta sobre ruta de acceso a Lago puelo desde la ruta 40, ruta de gran tránsito turístico, proveniente de las diversas localidades de El Hoyo, El Bolsón, El Maiten y Epuyen. En zona central de la Comarca Andina',
    price: 'USD 243.000',
    size: '2838',
    build: '550',
    cover: '550',
    rooms: '',
    bedrooms: '',
    bathroom: '3',
    storage: '',
    offices: '2',
    height: '7 m',
    garage: '6',
    access: '',
    floorSupport: ' t/m²',
    distanceToAsphalt: '',
    orientation: '',
    antiquity: '30 años',
  },
  {
    id: 10,
    title: 'Casas',
    name: 'CASA REMODELADA  2Has de Terreno, Barrio: Golondrinas, Lago Puelo, Chubut + casita ecológica con vidrio vitraux',
    carouselName: 'CHACRA con dos casas en Golondrinas',
    province: 'Chubut',
    location: 'Lago Puelo',
    address: 'Golondrinas, Lago Puelo, Chubut',
    locationX: '-71.4947512',
    locationY: '-42.0225625',
    imageUrl: 'https://347inmobiliaria.com/img/10/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/10/1.jpg',
      'https://347inmobiliaria.com/img/10/2.jpg',
      'https://347inmobiliaria.com/img/10/3.jpg',
      'https://347inmobiliaria.com/img/10/4.jpg',
      'https://347inmobiliaria.com/img/10/5.jpg',
      'https://347inmobiliaria.com/img/10/6.jpg',
      'https://347inmobiliaria.com/img/10/7.jpg',
      'https://347inmobiliaria.com/img/10/8.jpg',
      'https://347inmobiliaria.com/img/10/9.jpg',
      'https://347inmobiliaria.com/img/10/10.jpg',
      'https://347inmobiliaria.com/img/10/11.jpg',
      'https://347inmobiliaria.com/img/10/12.jpg',
      'https://347inmobiliaria.com/img/10/13.jpg',
      'https://347inmobiliaria.com/img/10/14.jpg',
      'https://347inmobiliaria.com/img/10/15.jpg',
      'https://347inmobiliaria.com/img/10/16.jpg',
      'https://347inmobiliaria.com/img/10/17.jpg',
      'https://347inmobiliaria.com/img/10/18.jpg',
      'https://347inmobiliaria.com/img/10/19.jpg',
      'https://347inmobiliaria.com/img/10/20.jpg',
      'https://347inmobiliaria.com/img/10/21.jpg',
      'https://347inmobiliaria.com/img/10/22.jpg',
      'https://347inmobiliaria.com/img/10/23.jpg',
      'https://347inmobiliaria.com/img/10/24.jpg',
      'https://347inmobiliaria.com/img/10/25.jpg',
      'https://347inmobiliaria.com/img/10/26.jpg',
      'https://347inmobiliaria.com/img/10/27.jpg',
      'https://347inmobiliaria.com/img/10/28.jpg',
      'https://347inmobiliaria.com/img/10/29.jpg',
      'https://347inmobiliaria.com/img/10/30.jpg',
      'https://347inmobiliaria.com/img/10/31.jpg',
      'https://347inmobiliaria.com/img/10/32.jpg',
      'https://347inmobiliaria.com/img/10/33.jpg',
      'https://347inmobiliaria.com/img/10/34.jpg',
      'https://347inmobiliaria.com/img/10/35.jpg',
      'https://347inmobiliaria.com/img/10/36.jpg',
      'https://347inmobiliaria.com/img/10/37.jpg',
      'https://347inmobiliaria.com/img/10/38.jpg',
      'https://347inmobiliaria.com/img/10/39.jpg',
      'https://347inmobiliaria.com/img/10/40.jpg',
      'https://347inmobiliaria.com/img/10/41.jpg',
      'https://347inmobiliaria.com/img/10/42.jpg',
      'https://347inmobiliaria.com/img/10/43.jpg',
      'https://347inmobiliaria.com/img/10/44.jpg',
      'https://347inmobiliaria.com/img/10/45.jpg',
      'https://347inmobiliaria.com/img/10/46.jpg',
      'https://347inmobiliaria.com/img/10/47.jpg',
      'https://347inmobiliaria.com/img/10/48.jpg',
      'https://347inmobiliaria.com/img/10/49.jpg',
      'https://347inmobiliaria.com/img/10/50.jpg',
      'https://347inmobiliaria.com/img/10/51.jpg',
      'https://347inmobiliaria.com/img/10/52.jpg',
      'https://347inmobiliaria.com/img/10/53.jpg',
      'https://347inmobiliaria.com/img/10/54.jpg',
      'https://347inmobiliaria.com/img/10/55.jpg',
      'https://347inmobiliaria.com/img/10/56.jpg',
      'https://347inmobiliaria.com/img/10/57.jpg',
      'https://347inmobiliaria.com/img/10/58.jpg',
      'https://347inmobiliaria.com/img/10/59.jpg',
      'https://347inmobiliaria.com/img/10/60.jpg',
      'https://347inmobiliaria.com/img/10/61.jpg',
      'https://347inmobiliaria.com/img/10/62.jpg',
      'https://347inmobiliaria.com/img/10/63.jpg',
      'https://347inmobiliaria.com/img/10/64.jpg',
      'https://347inmobiliaria.com/img/10/65.jpg',
      'https://347inmobiliaria.com/img/10/66.jpg',
      'https://347inmobiliaria.com/img/10/67.jpg',
      'https://347inmobiliaria.com/img/10/68.jpg',
      'https://347inmobiliaria.com/img/10/69.jpg',
      'https://347inmobiliaria.com/img/10/70.jpg',
      'https://347inmobiliaria.com/img/10/71.jpg',
      'https://347inmobiliaria.com/img/10/72.jpg',
      'https://347inmobiliaria.com/img/10/73.jpg',
      'https://347inmobiliaria.com/img/10/74.jpg',
      'https://347inmobiliaria.com/img/10/75.jpg',
      'https://347inmobiliaria.com/img/10/76.jpg',
      'https://347inmobiliaria.com/img/10/77.jpg',
      'https://347inmobiliaria.com/img/10/78.jpg',
      'https://347inmobiliaria.com/img/10/79.jpg',
      'https://347inmobiliaria.com/img/10/80.jpg',
      'https://347inmobiliaria.com/img/10/81.jpg',
      'https://347inmobiliaria.com/img/10/82.jpg',
      'https://347inmobiliaria.com/img/10/83.jpg',
      'https://347inmobiliaria.com/img/10/84.jpg'
    ],
    description: 'Área de Terreno  2Has PRECIOSA CASA REMODELADA de 77,5 sup  cub. Barrio: Golondrinas, Lago Puelo, Chubut + casita ecológica con vidrio vitraux. de 54,89 m2  Ideal para casa de huéspedes o alquilar en temporada o permanente. Preciosa chacra!!!, hermosas vistas hacia el cerro Piltriquitrón y la cordillera. Estufa a leña de alto rendimiento y muy buena calidad. Toda la casa es muy luminosa, Panel solar de 5,6 Watts y 4 baterías, tanque de reserva de agua y bomba presurizadora. Ambas construcciones Cuentan con cochera techada. Arboles autóctonos y frutales, con un arrollo que corre de lado a lado, Se respira paz, tranquilidad. Reserva de agua en tanque australiano de 30,000 lts. Pozo de agua. Elegir calidad de vida, vida de campo en la comarca Andina!!!! lugares turísticos por excelencia, cercano a El Bolsón, Lago Puelo y El Hoyo. OPCION ALQUILER/PERMUTA',
    price: 'USD 240.000',
    size: '20000',
    build: '106.5',
    cover: '77.5',
    rooms: '3',
    bedrooms: '2',
    bathroom: '1',
    garage: '1',
    storage: '1',
    floors: '1',
    orientation: 'Norte',
    antiquity: '1 año',
  },
  {
    id: 11,
    title: 'Casas',
    name: 'Casa En Venta Con Jardín Y Parque, Barrio Las Avenidas, Mar Del Plata, Buenos Aires. Amplios Ambientes, Gran Jardín',
    carouselName: 'Casa En Venta Con Jardín Y Parque, Barrio Las Avenidas, Mar Del Plata, Buenos Aires. Amplios Ambientes, Gran Jardín',
    province: 'Buenos Aires',
    location: 'Mar Del Plata',
    address: 'San Salvador 5690, Barrio Las Avenidas, Mar Del Plata, Buenos Aires',
    locationX: '-57.61023669969505',
    locationY: '-38.00349716797861',
    imageUrl: 'https://347inmobiliaria.com/img/11/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/11/1.jpg',
      'https://347inmobiliaria.com/img/11/2.jpg',
      'https://347inmobiliaria.com/img/11/3.jpg',
      'https://347inmobiliaria.com/img/11/4.jpg',
      'https://347inmobiliaria.com/img/11/5.jpg',
      'https://347inmobiliaria.com/img/11/6.jpg',
      'https://347inmobiliaria.com/img/11/7.jpg',
      'https://347inmobiliaria.com/img/11/8.jpg',
      'https://347inmobiliaria.com/img/11/9.jpg',
    ],
    description: '',
    price: 'USD 110.000',
    size: '110',
    build: '110',
    cover: '110',
    rooms: '5',
    bedrooms: '2',
    bathroom: '2',
    garage: '1',
    storage: '1',
    floors: '1',
    orientation: 'Oeste',
    antiquity: '50 años',
  },
  {
    id: 12,
    title: 'Terrenos',
    name: 'Gran Oportunidad De Inversion.!!!!. Lote Con Hermosas Vistas En El Hoyo, Chubut. Lugar Turístico, A 4 Cuadras Del Centro',
    carouselName: 'Gran Oportunidad De Inversion.!!!!. Lote Con Hermosas Vistas En El Hoyo, Chubut. Lugar Turístico, A 4 Cuadras Del Centro',
    province: 'Chubut',
    location: 'El Hoyo',
    address: 'A 4 Cuadras Del Centro del Hoyo',
    locationX: '-71.51762261718649',
    locationY: '-42.05868514583303',
    imageUrl: 'https://347inmobiliaria.com/img/12/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/12/1.jpg',
    ],
    description: 'Terreno en venta a 4 cuadras del centro e El Hoyo, en un barrio residencial, rodeado de montañas, calle paralela a la entrada a la famosa Catarata Corbata Blanca. en el corazón de la Comarca Andina. En precio, una gran oportunidad de inversión en un lugar de potencial crecimiento, calmo, armonioso, cerca todos los servicios, escuela, hospital, Municipio!!!, Elegir vivir en la naturaleza.',
    price: 'USD 25.000',
    size: '500',
    access: 'Asfalto',
    distanceToAsphalt: '0 km',
    orientation: '',
  },
  {
    id: 13,
    title: 'Casas',
    name: 'CASA PH a estrenar',
    carouselName: 'CASA PH a estrenar',
    province: 'Río Negro',
    location: 'El Bolsón',
    address: 'Plaza de los niños, Barrio Andén - El Bolson',
    locationX: '-71.52695167447857',
    locationY: '-41.97867817123091',
    imageUrl: 'https://347inmobiliaria.com/img/13/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/13/1.jpg',
      'https://347inmobiliaria.com/img/13/2.jpg',
      'https://347inmobiliaria.com/img/13/3.jpg',
      'https://347inmobiliaria.com/img/13/4.jpg',
      'https://347inmobiliaria.com/img/13/5.jpg',
      'https://347inmobiliaria.com/img/13/6.jpg',
      'https://347inmobiliaria.com/img/13/7.jpg',
      'https://347inmobiliaria.com/img/13/8.jpg',
      'https://347inmobiliaria.com/img/13/9.jpg',
    ],
    description: 'Casa a estrenar\nConstruidos 62,2mts2,\nTerreno 125 mts\n3 ambientes\n2 dormitorios\n1 baño completo con bañera o hidromasaje, ducha mamapara de vidrio, vanitorio de Cipres, paredes revestidas de Porcelanato rectificado, extractor.\nCocina con barra desayunador, mesada, alacena de Cipres extractor en acero inoxidable, artefacto de cocina con 4 hornallas y horno, heladera con freezer, instalaciones para lavavajilla.\nConstrucción y equipamiento:\nRevestimientos exterior de revear y Pirkas, aberturas y muebleario de Cipres,\nConstruccion con ladrillo de 18, Pisos de Porcelanato rectificado, calefactores ctz en cada ambiente,\nAire acondicionado frío/calor,\nPuertas Oblak de exterior y de placa las de interior\nMuros exteriores divisorios doble ladrillo de 12, lo que le brinda mayor aislación acústica.\nChapas y zingueria color negro,\nPortón de ingreso con Rejas a medida\nAlarma de seguridad, extractores cocina y baño. Grifería piazza Dot\nCada casa tiene su patio de ingreso con estacionamiento individual, jardín, con lavadero, y parrilla individual,\nTanque de reserva de agua de 900lts, Bomba presurizadora\nTermotanque a gas\nSistema de alarma\nServicios de electricidad, agua de red, gas natural a instalar, cloacas, perforación para agua de riego.\nSe encuentra en un Barrio armado, por lo que no hay ruidos de construcción, una zona muy tranquila, con Plaza de los niños 1 1/2 cuadra, a 2 cuadras ruta 40 y 3 cuadras del supermercado.\n-Opción compra terminado US$89.000.-\n-Opcion de compra en Pozo al valor de US$ 75.000: 1 er entrega en el 30%, y el restante 70% con financiamiento en 7 u 8 cuotas .\nTiempo de entrega: 6 meses, con posibilidad de elegir color porcelanato, cocina, etc.\nPH aprobado,\nCon Escritura',
    price: 'USD 75.000',
    size: '125',
    build: '62',
    cover: '62',
    rooms: '3',
    bedrooms: '2',
    bathroom: '1',
    garage: '1',
    storage: '',
    floors: '',
    orientation: '',
    antiquity: '0 años',
  },
  {
    id: 15,
    title: 'Terrenos',
    name: 'En Venta Dos Lotes De 600 M² C/u En Epuyen, Zona Turística, Rodeado De Naturaleza Y Tranquilidad',
    carouselName: 'Ultimo terreno en condominio de 600 mts en Epuyen, en casco urbano, vecindario tranquilo',
    province: 'Chubut',
    location: 'Epuyén',
    address: 'Los Notros 912, Epuyén, Chubut',
    locationX: '-71.36511153792695',
    locationY: '-42.23228645951115',
    imageUrl: 'https://347inmobiliaria.com/img/15/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/15/1.jpg',
      'https://347inmobiliaria.com/img/15/2.jpg',
      'https://347inmobiliaria.com/img/15/3.jpg',
    ],
    description: 'Son dos lotes cada uno de una medida aproximada de 600 m², En Casco Urbano de Epuyén. Gas natural a 2 cuadras, lo trajeron con todos los vecinos, es solo instalarlo. Calle Los Notros 200 mts del asfalto y cercano al centro, escuela, transporte público, Hospital. Terreno Plano, con suave pendiente. Lote nro. 2: Frente: aprox 21,80 mts, fondo 13,72 mts, Lado derecho: 33,17 mts. lado Izquierdo: 35,87mts. Lote nro. 3: Frente: aprox 10,36,mts, fondo 18,42 mts, Lado derecho: 32,32 mts. lado Izquierdo: 33,17 Cercano al maravilloso Lago Epuyen!!!',
    price: 'USD 18.000',
    size: '600',
    access: 'Ripio',
    distanceToAsphalt: '200 m',
    orientation: '',
  },
  {
    id: 17,
    title: 'Terrenos',
    name: 'Excelente Ubicacion, Frente Ambplio, Hermoso Terreno En Pendiente, Paralelo A Ruta 40, Increíbles Vistas',
    carouselName: 'Terreno Excelente ubicación 1/2 Hra. Villa Turismo, El Bolsón',
    province: 'Río Negro',
    location: 'El Bolsón',
    address: 'Ruta 40 Sur Nº 179, El Bolsón, Río Negro',
    locationX: '-71.52197005110993',
    locationY: '-41.98928554072235',
    imageUrl: 'https://347inmobiliaria.com/img/17/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/17/1.jpg',
      'https://347inmobiliaria.com/img/17/2.jpg',
      'https://347inmobiliaria.com/img/17/3.jpg',
      'https://347inmobiliaria.com/img/17/4.jpg',
      'https://347inmobiliaria.com/img/17/5.jpg',
      'https://347inmobiliaria.com/img/17/6.jpg',
      'https://347inmobiliaria.com/img/17/7.jpg',
      'https://347inmobiliaria.com/img/17/8.jpg',
      'https://347inmobiliaria.com/img/17/9.jpg',
      'https://347inmobiliaria.com/img/17/10.jpg',
      'https://347inmobiliaria.com/img/17/11.jpg',
      'https://347inmobiliaria.com/img/17/12.jpg',
      'https://347inmobiliaria.com/img/17/13.jpg',
      'https://347inmobiliaria.com/img/17/14.jpg',
      'https://347inmobiliaria.com/img/17/15.jpg',
      'https://347inmobiliaria.com/img/17/16.jpg',
      'https://347inmobiliaria.com/img/17/17.jpg',
      'https://347inmobiliaria.com/img/17/18.jpg',
    ],
    description: 'INMEJORABLE UBICACION EN VILLA TURISMO!!! Zona: Residencial y turística. Terreno con leve pendiente, tiene álamos y pinos. DETALLES: vista panorámica al centro de El Bolsón y a las montañas de la cordillera por el Este y el Piltriquitrón hacia el Oeste, ideal para emprendimiento turístico ya que cuenta con gran frente de 53 mts. dando a la ruta 40. Escritura independiente. SERVICIOS: Agua corriente, gas natural y de electricidad en Puerta. En calle paralela a ruta 40, a tan solo 3 km del centro del Bolsón: hay hospital, escuelas, centro comercial, a 100 mts de ruta 40 y de transporte público. ATRACTIVOS TURÍSTICOS CERCANOS Y LUGARES DE ESPARCIMIENTO: Feria Regional de El Bolsón, Cerro de la Cruz con vista panorámica al pueblo, ubicacion inmejorable, ceca del centro, y a la vez apartado, de muy facil acceso a todos los lugares turísticos, en 15 minutos estás en El Hoyo (el laberinto, lago en Puerto Patriada, catarata corbata blanca), en 15 minutos estas también en Lago Puelo (Parque Nacional de Lago Puelo, pasarela del Motoco, mirador del Blaco), y tantos otros atractivos turísticos',
    price: 'USD 110.000',
    size: '4924.28',
    access: 'Ripio',
    distanceToAsphalt: '300 m',
    orientation: '',
  },
  {
    id: 19,
    title: 'Terrenos',
    name: 'Excelente Ubicación Lotes De 2.500 M² En El Bolson, Tremenda Vista Al Piltri Y La Cordillera!!!',
    carouselName: 'Lotes en venta de 2.500 m² en El Bolsón. Tremenda vista al Piltri y la cordillera!!! Excelente ubicación',
    province: 'Río Negro',
    location: 'El Bolsón',
    address: 'Los Pioneros Sn, Villa Turismo, El Bolsón',
    locationX: '-71.52503013380152',
    locationY: '-41.97335463766216',
    imageUrl: 'https://347inmobiliaria.com/img/19/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/19/1.jpg',
      'https://347inmobiliaria.com/img/19/2.jpg',
      'https://347inmobiliaria.com/img/19/3.jpg',
      'https://347inmobiliaria.com/img/19/4.jpg',
      'https://347inmobiliaria.com/img/19/5.jpg',
      'https://347inmobiliaria.com/img/19/6.jpg',
      'https://347inmobiliaria.com/img/19/7.jpg',
      'https://347inmobiliaria.com/img/19/8.jpg',
      'https://347inmobiliaria.com/img/19/9.jpg',
      'https://347inmobiliaria.com/img/19/0.jpg',
      'https://347inmobiliaria.com/img/19/11.jpg',
      'https://347inmobiliaria.com/img/19/12.jpg',
      'https://347inmobiliaria.com/img/19/13.jpg',
      'https://347inmobiliaria.com/img/19/14.jpg',
      'https://347inmobiliaria.com/img/19/15.jpg',
      'https://347inmobiliaria.com/img/19/16.jpg',
      'https://347inmobiliaria.com/img/19/17.jpg',
      'https://347inmobiliaria.com/img/19/18.jpg',
      'https://347inmobiliaria.com/img/19/19.jpg',
      'https://347inmobiliaria.com/img/19/20.jpg',
      'https://347inmobiliaria.com/img/19/21.jpg',
      'https://347inmobiliaria.com/img/19/22.jpg',
      'https://347inmobiliaria.com/img/19/23.jpg',
      'https://347inmobiliaria.com/img/19/24.jpg',
      'https://347inmobiliaria.com/img/19/25.jpg',
    ],
    description: 'Loteo de 2 Has, son 8 lotes PH especial. Proyecto Country cerrado, listo para escriturar!!!! Cada Lote tiene 2.500 m². Un lugar cerca al centro de El Bolson y a la vez apartado, rodeado de naturaleza, vistas maravillosas para disfrutar cada dia!!!, a 1 cuadra de ruta 40. Super oportunidad están en USD$ 75.000.- c/u',
    price: 'USD 75.000',
    size: '2500',
    access: 'Asfalto',
    distanceToAsphalt: '',
    orientation: '',
  },
  {
    id: 20,
    title: 'Casas',
    province: 'Río Negro',
    name: 'Exclusiva Casa En Venta , Barrio Villa Turismo, El Bolson 347 Inmobiliaria',
    carouselName: 'Exclusiva casa en venta, Villa Turismo, El Bolsón',
    location: 'El Bolsón',
    address: 'Calle Los Pioneros 2000, Villa Turismo, El Bolsón, Río Negro',
    locationX: '-71.5223845522159',
    locationY: '-41.97287821770239',
    imageUrl: 'https://347inmobiliaria.com/img/20/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/20/1.jpg',
      'https://347inmobiliaria.com/img/20/2.jpg',
      'https://347inmobiliaria.com/img/20/3.jpg',
      'https://347inmobiliaria.com/img/20/4.jpg',
      'https://347inmobiliaria.com/img/20/5.jpg',
      'https://347inmobiliaria.com/img/20/6.jpg',
      'https://347inmobiliaria.com/img/20/7.jpg',
      'https://347inmobiliaria.com/img/20/8.jpg',
      'https://347inmobiliaria.com/img/20/9.jpg',
      'https://347inmobiliaria.com/img/20/10.jpg',
      'https://347inmobiliaria.com/img/20/11.jpg',
      'https://347inmobiliaria.com/img/20/12.jpg',
    ],
    description: 'Lote en PH de 15.000 m2\n-Casa principal\nSuperficie cubierta aprox. 467 m2\nPlanta Alta:\nDormitorios.: 2 (uno con doble salida a balcón), Baño: 1\nOtros espacios: cuarto de blanquería, pequeña habitación extra, playroom o estudio\nPlanta Baja:\nAmplio Living con doble entrada, chimenea, Comedor , toilette, Cocina con ingreso del jardín y Comedor de diario, Lavadero amplio con placards y secadores toalleros, Dormitorios: 3: 1 con walking closet y baño en suite con Bañera hidromasaje, 2 con baño en suite\n\n-Casa de huéspedes :\nSuperficie cubierta aprox. 100 m2\n1 dormitorio\n1 baño completo\nCocina comedor con parrilla\n\n-Cabaña\nSuperficie cubierta aprox 90 m2\n1 dormitorio, 1 baño completo\nCocina\nLiving Comedor\n\nCochera: Superficie semi cubierta aprox. 80 m2\nAntiguedad: aprox. 10 años\nCaracterísticas de la propiedad:\nHabilitada para hotel Boutique, Porche de piedra con acceso por escalera, Piscina, Calefacción central con radiadores, Vidrio DVH\nPisos Ébano y Roble, chimenea, Porcelanato, Doble balcón en habitación planta alta, Placards Empotrados, Jardín parquizado, Toalleros Radiadores\nTecho a dos aguas de chapa con cobertura estilo teja, Vistas panorámicas 360 al Piltriquitrón y la pre Cordillera , Gas natural, calefacción central con radiadores, perforación de agua, cisterna, Cerco perimetral en toda la propiedad\nLa zona residencial tranquila y fácil acceso al centro, a tan solo una cuadra de RN 40\nEn las faldas del Piltriquitrón',
    price: 'USD 1.100.000',
    size: '15000',
    build: '657',
    cover: '657',
    rooms: '8',
    bedrooms: '5',
    bathroom: '5',
    storage: '2',
    garage: '2',
    floors: '',
    orientation: 'Este',
    antiquity: '10 años',
  },
  {
    id: 21,
    title: 'Chacras',
    province: 'Chubut',
    name: 'Oportunidad!!!! Preciosa Chacra De 4 Has, Super Precio, Ideal Emprendimiento Turístico, Con Arroyo, Bosque, En El Hoyo, Chubut',
    carouselName: 'Chacra de 4 Has. SE VENDE, en El Hoyo, camino a Puerto Patriada',
    location: 'El Hoyo',
    address: 'Callejón Ollagua',
    locationX: '-71.52529873235727',
    locationY: '-42.10637368340776',
    imageUrl: 'https://347inmobiliaria.com/img/21/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/21/1.jpg',
      'https://347inmobiliaria.com/img/21/2.jpg',
      'https://347inmobiliaria.com/img/21/3.jpg',
      'https://347inmobiliaria.com/img/21/4.jpg',
      'https://347inmobiliaria.com/img/21/5.jpg',
      'https://347inmobiliaria.com/img/21/6.jpg',
      'https://347inmobiliaria.com/img/21/7.jpg',
      'https://347inmobiliaria.com/img/21/8.jpg',
      'https://347inmobiliaria.com/img/21/9.jpg',
      'https://347inmobiliaria.com/img/21/10.jpg',
    ],
    description: 'Preciosa chacra de 4 Hectáreas. Leíste bien son CUATRO HECTÁREAS!!!!!, IDEAL EMPRENDIMIENTO TURÍSTICO DE CATEGORÍA TIPO GLAMPING, en la Localidad de El Hoyo de la Comarca Andina, sobre las faldas del cerro Pirque, con increíbles vistas hacia el cerro currumahuida, camino a Puerto Patriada, donde está el emblemático lago Epuyen, zona turística por excelencia, a tan solo 4,5km del centro y 3,6km de ruta 40, el terreno cuenta con arroyo propio que provee de agua todo el año.\nBosque nativo: Pitras, Maitenes, Radales, cipreses, etc. Frutales cerezos, manzanos, maqui, rosa mosqueta.\nCabaña con cocina, baño y entre piso\nGran frente de 140,20\nEscritura individual. Servicios (el gas natural se encuentra a 10 mts de la cabaña)',
    price: 'USD 192.000',
    size: '40000',
    build: '',
    cover: '',
    rooms: '',
    bedrooms: '',
    bathroom: '',
    storage: '',
    garage: '',
    floors: '',
    orientation: '',
    antiquity: '',
    access: 'Ripio',
  },
  {
    id: 23,
    title: 'Chacras',
    province: 'Río Negro',
    name: 'Elegante chacra de 4748 m², con casa de 220 m², Villa Turismo, El Bolsón',
    carouselName: 'Chacra de 4.748 m², con CASA de 220 m², Villa Turismo, El Bolsón',
    location: 'El Bolsón',
    address: '',
    locationX: '-71.51944823336127',
    locationY: '-41.98861570072635',
    imageUrl: 'https://347inmobiliaria.com/img/23/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/23/1.jpg',
      'https://347inmobiliaria.com/img/23/2.jpg',
      'https://347inmobiliaria.com/img/23/3.jpg',
      'https://347inmobiliaria.com/img/23/4.jpg',
      'https://347inmobiliaria.com/img/23/5.jpg',
      'https://347inmobiliaria.com/img/23/6.jpg',
      'https://347inmobiliaria.com/img/23/7.jpg',
      'https://347inmobiliaria.com/img/23/8.jpg',
    ],
    description: 'CASA con muy buena distribución y ambientes amplios, tiene pisos de madera, amplios ventanales y en todo el jardín hermosas vistas a la Cordillera y al cerro Piltriquitrón. Una zona muy tranquila, excelente ubicación, en el cotizado barrio de Villa Turismo con mucha naturaleza y a muy poca distancia del centro. Suave pendiente con arroyo que cruza el predio, vegetación nativa y árboles frutales (Nogales, manzanos, y cerezos) para consumo personal Árboles nativos: Cipreses, Radales y Maitenes. Casa de dos plantas, living con chimenea y comedor con cocina integrada, cuatro dormitorios, un baño y lavadero. Cochera para un auto.',
    price: 'USD 220.000',
    size: '4748',
    build: '220',
    cover: '220',
    rooms: '5',
    bedrooms: '4',
    bathroom: '2',
    storage: '1',
    garage: '1',
    floors: '2',
    orientation: '',
    antiquity: '30 años',
    access: 'Ripio',
    distanceToAsphalt: '0.5 km',
  },
  {
    id: 24,
    title: 'Casas',
    province: 'Río Negro',
    name: 'Casa Amplios Ambientes En El Bolson Centro',
    carouselName: 'CASA amplios ambientes en El Bolsón centro',
    location: 'El Bolsón',
    address: 'Balcarce',
    locationX: '-71.5292452125091',
    locationY: '-41.95804455396961',
    imageUrl: 'https://347inmobiliaria.com/img/24/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/24/1.jpg',
      'https://347inmobiliaria.com/img/24/2.jpg',
      'https://347inmobiliaria.com/img/24/3.jpg',
      'https://347inmobiliaria.com/img/24/4.jpg',
      'https://347inmobiliaria.com/img/24/5.jpg',
      'https://347inmobiliaria.com/img/24/6.jpg',
      'https://347inmobiliaria.com/img/24/7.jpg',
      'https://347inmobiliaria.com/img/24/8.jpg',
      'https://347inmobiliaria.com/img/24/9.jpg',
      'https://347inmobiliaria.com/img/24/10.jpg',
    ],
    description: 'CASA de una planta con altillo para playroom u oficina en EL BOLSON, muy buena ubicacion en esquina zona residencial en el centro de El Bolsón:\n160 m2 construidos aproximadamente\n2 dormitorios: EL principal en suite con walking closet y salida al jardin\n2 baños\nliving con chimenea\nconfortable comedor\ncocina con varios muebles y ventanal hacia la calle con vista a la cordillera\nlavadero aparte\narmario para alacena\n1 dormitorio de visita con toilette afuera\nParrilla y taller\nAmplios ambientes, grandes ventanales.\nConstruida sobre dos lotes 996 m2 Total\nOrientación: Norte\nTerreno Plano, con suave pendiente, algunos árboles frutales.',
    price: 'USD 200.000',
    size: '996',
    build: '180',
    cover: '180',
    rooms: '4',
    bedrooms: '3',
    bathroom: '3',
    storage: '1',
    garage: '1',
    floors: '',
    orientation: 'Norte',
    antiquity: '15 años',
  },
  {
    id: 25,
    title: 'Terrenos',
    province: 'Chubut',
    name: 'Lotes Con Excelente Ubicación, A Metros Del Parque Nacional Lago Puelo, Comarca Andina',
    carouselName: 'Loteo Kalfuco de 2.000 m²',
    location: 'Lago Puelo',
    address: 'Las Bandurrias',
    locationX: '-71.60290157200279',
    locationY: '-42.08916040474563',
    imageUrl: 'https://347inmobiliaria.com/img/25/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/25/1.jpg',
      'https://347inmobiliaria.com/img/25/2.jpg',
      'https://347inmobiliaria.com/img/25/3.jpg',
      'https://347inmobiliaria.com/img/25/4.jpg',
      'https://347inmobiliaria.com/img/25/5.jpg',
      'https://347inmobiliaria.com/img/25/6.jpg',
      'https://347inmobiliaria.com/img/25/7.jpg',
      'https://347inmobiliaria.com/img/25/8.jpg',
      'https://347inmobiliaria.com/img/25/9.jpg',
    ],
    description: 'Preciosos Lotes en Villa del Lago, exclusiva zona residencial, sin ser Barrio Privado, pero como si fuera Barrio Privado, un lugar cercado, con vistas panorámicas a las montañas, cuenta con nogales, la distancia perfecta entre vecinos, un lugar tranquilo, se vive en armonía con la naturaleza,\nTierra cultivable!!!!\nElije el lote a tu medida:\nLote 40 de 1.665 m2, gas natural a 50 metros Precio u$s 38.000.-\nLotes de 2.000 m2:\nLote 16 Precio u$s 38.500\nLotes 6/8/11 Precio u$s 39.500\nLote 4 y Lote 39, gas natural a 40 metros. Precio u$s 47.500.\nLote 10 de 2.000 m2 Precio u$s 43.000\nLotes 1/2/3/5/7/9/19/28/29 con gas natural en puerta u$s 52.500\nServicios subterráneos de agua, luz y gas, lo que hace que estén mas protegidos de la intemperie, y que no interfieran con el paisaje.\nEscritura individual inmediata dentro de los 45 días.\nContactanos para visitar!!!!',
    price: 'USD 38.000',
    size: '2000',
    access: 'Ripio',
    orientation: 'Norte',
  },
  {
    id: 26,
    title: 'Terrenos',
    province: 'Río Negro',
    name: 'Terrenos Camino Al Cerro Perito Moreno En Mallin Ahogado',
    carouselName: 'Terrenos en condominio camino al Cerro Perito Moreno en Mallin Ahogado',
    location: 'Mallin Ahogado',
    address: '',
    locationX: '-71.50426750760245',
    locationY: '-41.839566702083836',
    imageUrl: 'https://347inmobiliaria.com/img/26/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/26/1.jpg',
      'https://347inmobiliaria.com/img/26/2.jpg',
      'https://347inmobiliaria.com/img/26/3.jpg',
      'https://347inmobiliaria.com/img/26/4.jpg',
      'https://347inmobiliaria.com/img/26/5.jpg',
      'https://347inmobiliaria.com/img/26/6.jpg',
    ],
    description: 'INCREÍBLE OPORTUNIDAD!!! Gran potencial turístico ya que están camino al centro de ski Laderas, en lo alto de la montaña de Mallin Ahogado en El Bolsón, con unas vistas panorámicas, una paz y silencio que armonizan la calidad de vida.\nCon arroyo en el terreno\nTerrenos en condominio de aprox. 2.000 mts. cada uno, en el cerro de Mallin Ahogado!!!! Recién lanzamos la venta y ya se vendieron 3, no pierdas la oportunidad de capitalizarte en la comarca Andina.\nEl FOS es del 5% y el FOT del 10%\nA 4,5 kmts de Warton y 6 kms del centro de ski.\nTremendo potencial de crecimiento, ya que toda la zona se esta desarrollando y creciendo turisticamente, preservando el entorno natural.\nLos terrenos mas altos están en el valor de USD$ 15.000 Y los mas cercanos al camino de ingreso están en USD$ 20.000.-\nEn uno de los terrenos de 2500 se está construyendo una casa, y así a medio construir tiene un valor de USD $29.000\n\nEl ingreso al Cerro está asfaltado a nuevo!!',
    price: 'USD 15.000',
    size: '2000',
    access: 'Ripio',
  },
  {
    id: 30,
    title: 'Terrenos',
    province: 'Río Negro',
    name: 'Terrenos Costa Río Azul El Bolsón',
    carouselName: 'Lotes Costa Río Azul, El Bolsón',
    location: 'El Bolsón',
    address: '',
    locationX: '-71.56520141085159',
    locationY: '-41.956841116426425',
    imageUrl: 'https://347inmobiliaria.com/img/30/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/30/1.jpg',
      'https://347inmobiliaria.com/img/30/2.jpg',
      'https://347inmobiliaria.com/img/30/3.jpg',
      'https://347inmobiliaria.com/img/30/4.jpg',
      'https://347inmobiliaria.com/img/30/5.jpg',
    ],
    description: 'Hermoso terreno que da a la Costa del Río Azul. Rodeado de bosques con simples senderos que conducen a lugares de ensueño. El estar en la costa del Río Azul, un flujo de agua pura de deshielo que por el entorno y el cielo tanlimpio le da un color azul maravilloso y a esto debe su nombre, le da un toque de fantasía.\nNo espere más comunicate con nosotros para ir a conocerlo.',
    price: 'USD 80.000',
    size: '4531',
    access: 'Tierra',
  },
  {
    id: 'HB001',
    title: 'Casas',
    province: 'Chubut',
    name: 'CASA En Golondrinas, Lago Puelo',
    carouselName: 'CASA En Golondrinas, Lago Puelo',
    location: 'Golondrinas',
    address: 'Callejon del Sol',
    locationX: '-71.538823715869',
    locationY: '-42.024592467108',
    imageUrl: 'https://347inmobiliaria.com/img/HB001/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/HB001/1.jpg',
      'https://347inmobiliaria.com/img/HB001/2.jpg',
      'https://347inmobiliaria.com/img/HB001/3.jpg',
      'https://347inmobiliaria.com/img/HB001/4.jpg',
      'https://347inmobiliaria.com/img/HB001/5.jpg',
      'https://347inmobiliaria.com/img/HB001/6.jpg',
      'https://347inmobiliaria.com/img/HB001/7.jpg',
      'https://347inmobiliaria.com/img/HB001/8.jpg',
      'https://347inmobiliaria.com/img/HB001/9.jpg',
      'https://347inmobiliaria.com/img/HB001/10.jpg',
      'https://347inmobiliaria.com/img/HB001/11.jpg',
    ],
    description: 'CASA DE DOS PLANTAS CON GRAN JARDIN\nUBICACIÓN: ZONA RURAL “LAS GOLONDRINAS” A 600 metros de RN 40 Sur\n• LOTE: 900 MT2 PARQUIZADOS CON ARBOLES Y PLANTAS ORNAMENTALES\n• SUPERFICIE CONSTRUIDA: 117 M2 EN DOS PLANTAS\n• PLANTA ALTA:\n• 2 DORMITORIOS\n• 1 BAÑO C/ ANTEBAÑO\n• POSIBILIDAD DE AMPLIACION PARA SUITE\n• ACCESO POR ESCALERA DE MADERA CON SEGURIDDAD PARA NIÑOS\nPLANTA BAJA:\n• LIVING, COCINA COMEDOR CONCEPTO ABIERTO C/PARRILLA A TERMINAR\n• PUERTAS FRANCESAS AL PARQUE\n• 1 CUARTO PARA GUARDADO C/ ENTRADA O SALIDA ALTERNATIVA AL FRENTE\n• 1 BAÑO A TERMINAR\n• ANTEBAÑO USADO PARA LAVARROPAS\nPISOS CERAMICOS, ABERTURAS Y MATERIALES DE PRIMERA CALIDAD.\nCON SERVICIOS DE LUZ Y AGUA Y GAS PARA CONEXIÓN INMEDIATA.\nSISTEMA DE CALEFACCIÓN A RADIADORES CON CALDERA.\nSISTEMA DE BIODIGESTOR\n158.000 DÓLARES\nSE ESCUCHAN OFERTAS!',
    price: 'USD 158.000',
    size: '900',
    build: '117',
    cover: '117',
    rooms: '3',
    bedrooms: '2',
    bathroom: '1',
    storage: '',
    garage: '2',
    floors: '2',
    orientation: '',
    antiquity: '3 años',
  },
  {
    id: 'HB002',
    title: 'Terrenos',
    province: 'Chubut',
    name: 'Terreno en El Hoyo Comarca Andina',
    carouselName: 'Terreno en El Hoyo Comarca Andina',
    location: 'El Hoyo',
    address: 'Callejon Ponce',
    locationX: '-71.527474196301',
    locationY: '-42.068278163001',
    imageUrl: 'https://347inmobiliaria.com/img/HB002/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/HB002/1.jpg',
      'https://347inmobiliaria.com/img/HB002/2.jpg',
      'https://347inmobiliaria.com/img/HB002/3.jpg',
      'https://347inmobiliaria.com/img/HB002/4.jpg',
      'https://347inmobiliaria.com/img/HB002/5.jpg',
      'https://347inmobiliaria.com/img/HB002/6.jpg',
      'https://347inmobiliaria.com/img/HB002/7.jpg',
      'https://347inmobiliaria.com/img/HB002/8.jpg',
      'https://347inmobiliaria.com/img/HB002/9.jpg',
    ],
    description: 'Lote en esquina,\nSe ingresa por ruta 40, a tres cuadras del centro de El Hoyo\nson 339 m² , en condominio\ntodo cercado,\nEn una zona super tranquila, rodeada de montañas\nLugares turísitcos próximos: Laberinto de El Hoyo, Puerto Patriada, Catarata Corbata Blanca,',
    price: 'USD 20.000',
    size: '339',
    access: '',
  },
  {
    id: 'HB003',
    title: 'Duplex',
    province: 'Chubut',
    name: 'Duplex de estreno en Lago Puelo',
    carouselName: 'Duplex de estreno en Lago Puelo',
    location: 'Lago Puelo',
    address: 'Callejon Cortada al 300',
    locationX: '-71.597168715344',
    locationY: '-42.042276652615',
    imageUrl: 'https://347inmobiliaria.com/img/HB003/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/HB003/1.jpg',
      'https://347inmobiliaria.com/img/HB003/2.jpg',
      'https://347inmobiliaria.com/img/HB003/3.jpg',
      'https://347inmobiliaria.com/img/HB003/4.jpg',
      'https://347inmobiliaria.com/img/HB003/5.jpg',
      'https://347inmobiliaria.com/img/HB003/6.jpg',
      'https://347inmobiliaria.com/img/HB003/7.jpg',
      'https://347inmobiliaria.com/img/HB003/8.jpg',
      'https://347inmobiliaria.com/img/HB003/9.jpg',
      'https://347inmobiliaria.com/img/HB003/10.jpg',
      'https://347inmobiliaria.com/img/HB003/11.jpg',
      'https://347inmobiliaria.com/img/HB003/12.jpg',
      'https://347inmobiliaria.com/img/HB003/13.jpg',
    ],
    description: 'Duplex en Condominio\nconsta de 95,26 m² de terreno\nIngreso con espacio para estacionamiento de aprox. 25 m²\nPatio trasero cercado de aprox.20 m²\nDuplex de aprox. 90 m² Construídos\nPlanta Baja: living, comedor/cocina con ventanas pequeñas en alto y salida al patio trasero.\nToilette\nEscalera en hierro con escalones de madera y mueble empotrado\nPlanta alta 2 dormitorios: 1 dormitorio con vestidor y amplio ventanal\n1 baño completo\n1 dormitorio con espacio para dos camas\nPisos de cerámico, amplios ventanales en el living y habitación principal\nventanas con vidrio simple y marcos de aluminio\nCerco perimetral de entrada que divide los dúplex.\nIngreso camino de ripio (300 mts de ruta Provincial 16)\nEstufas en cada ambiente\nServicios: Electricidad, gas natural, agua.\nEstado de conservación y mantenimiento del inmueble excelente\nAntigüedad 2 años\nA 300 mts de Ruta Provincial 16 y Parada de colectivo\nLa zona residencial y fácil acceso al centro de Lago Puelo 2 km por ruta 16\nOrientación: Norte\nVistas a las montañas',
    price: 'USD 69.000',
    size: '95',
    build: '90',
    cover: '90',
    rooms: '3',
    bedrooms: '2',
    bathroom: '2',
    storage: '',
    garage: '1',
    floors: '2',
    orientation: 'Norte',
    antiquity: '2 años',
  },
  {
    id: 'HB004',
    title: 'Terrenos',
    province: 'Chubut',
    name: 'Terreno en Villa del Lago',
    carouselName: 'Terreno en Villa del Lago',
    location: 'Lago Puelo',
    address: '',
    locationX: '-71.610601218091',
    locationY: '-42.085829534271',
    imageUrl: 'https://347inmobiliaria.com/img/HB004/1.jpg',
    images: [
      'https://347inmobiliaria.com/img/HB004/1.jpg',
      'https://347inmobiliaria.com/img/HB004/2.jpg',
      'https://347inmobiliaria.com/img/HB004/3.jpg',
      'https://347inmobiliaria.com/img/HB004/4.jpg',
      'https://347inmobiliaria.com/img/HB004/5.jpg',
      'https://347inmobiliaria.com/img/HB004/6.jpg',
      'https://347inmobiliaria.com/img/HB004/7.jpg',
      'https://347inmobiliaria.com/img/HB004/8.jpg',
      'https://347inmobiliaria.com/img/HB004/9.jpg',
      'https://347inmobiliaria.com/img/HB004/10.jpg',
    ],
    description: 'Terreno con desnivel de 1.000 mt2\nFOS 20%\nÁrboles nativos y frutales.\nen Calle sin salida, lo que le da intimidad y mayor seguridad.\nFrente a plaza de juegos, a metros de la portada del Parque Nacional Lago Puelo.\nCon acceso a los servicios de luz, agua y gas.\nA metros del parque Nacional de Lago Puelo.\nZona residencial turística.',
    price: 'USD 38.000',
    size: '1045',
    access: '',
  },
  {
    id: 'CBR01',
    title: 'Terrenos',
    province: 'Chubut',
    name: 'Lotes En Lago Puelo Excelente Ubicación, Preciosas Vistas A Los Cerros Y Montañas, Cercano Al Rio Azul',
    carouselName: 'Lotes En Lago Puelo Excelente Ubicación, Preciosas Vistas A Los Cerros Y Montañas, Cercano Al Rio Azul',
    location: 'Lago Puelo',
    address: 'Camino viejo hacia El Bolsón',
    locationX: '-71.5904083',
    locationY: '-42.0262766',
    imageUrl: 'https://347inmobiliaria.com/img/CBR01/1.JPG',
    images: [
      'https://347inmobiliaria.com/img/CBR01/1.JPG',
      'https://347inmobiliaria.com/img/CBR01/2.JPG',
      'https://347inmobiliaria.com/img/CBR01/3.JPG',
      'https://347inmobiliaria.com/img/CBR01/4.JPG',
      'https://347inmobiliaria.com/img/CBR01/5.JPG',
      'https://347inmobiliaria.com/img/CBR01/6.JPG',
      'https://347inmobiliaria.com/img/CBR01/7.JPG',
      'https://347inmobiliaria.com/img/CBR01/8.JPG',
      'https://347inmobiliaria.com/img/CBR01/9.JPG',
      'https://347inmobiliaria.com/img/CBR01/10.JPG',
      'https://347inmobiliaria.com/img/CBR01/11.JPG',
      'https://347inmobiliaria.com/img/CBR01/12.JPG',
      'https://347inmobiliaria.com/img/CBR01/13.JPG',
    ],
    description: 'Importantes lotes en la zona más residencial del legendario barrio de Madereras en Lago Puelo!!!\nPrecio desde USD $48.000\nSuperficie aproximada de 2000 M2\nFOS 40%\nLotes con excelentes vistas panorámicas a los cerros y montañas típicas del lugar como el piltriquitron, el Morrudo, el Currumahuida, árboles nativos, además de pinos y sauces que embellecen el lugar. Uno de los lotes en esquina, da a dos calles, otro lote en calle interna del loteo y uno más sobre el camino!!!\nUna ubicación estratégica que cuenta con distintos accesos. En esquina, cerca la rotonda que da acceso hacia El Bolsón, Radal, El Hoyo, y el centro de Lago Puelo. Un Pequeño y diverso centro comercial a 2 cuadras. En la esquina está la parada de colectivo, y a 5 cuadras el río azúl !!!\nServicio eléctrico y alumbrado público, agua y el gas de red está a tan solo una cuadra.\n-Parcela 7 en ESQUINA Lote rectangular , frente de 24,95, fondo de 73,16 y 56,34 al otro lado, contra frente de 24,84. Superficie de 1800 m²\n-Parcela 8 contigua a la 7 SOBRE LA RUTA camino viejo, frente de 38,47, Fondo lateral de 48,30 y 38,13, contra frente de 50,14. Un inicio de construcción con platea y medias paredes. Superficie de 1.884,11 m²\n-Parcela 108 CAMINO INTERNO, Frente 31,37, fondo 62,07, contra frente 31,35 pozo de agua.\nSúper Paz y armonía para vivir rodeado de verde y un buen vecindario.',
    price: 'USD 48.000',
    size: '1800',
    access: '',
  },

  // VENDIDOS O QUITADOS
  // {
  //   id: 13,
  //   title: 'Terrenos',
  //   name: 'Terreno En Mallin Al Pie Del Cerro Saturnino, Antes De Pampa De Mallín Con Hermosas Vistas',
  //   address: 'Al pie del cerro Saturnino, antes de Pampa de Mallin',
  //   locationX: '-71.4888762',
  //   locationY: '-41.8681875',
  //   imageUrl: 'https://347inmobiliaria.com/img/13/1.jpg',
  //   images: [
  //     'https://347inmobiliaria.com/img/13/1.jpg',
  //     'https://347inmobiliaria.com/img/13/2.jpg',
  //     'https://347inmobiliaria.com/img/13/3.jpg',
  //     'https://347inmobiliaria.com/img/13/4.jpg',
  //     'https://347inmobiliaria.com/img/13/5.jpg',
  //     'https://347inmobiliaria.com/img/13/6.jpg',
  //     'https://347inmobiliaria.com/img/13/7.jpg',
  //     'https://347inmobiliaria.com/img/13/8.jpg',
  //     'https://347inmobiliaria.com/img/13/9.jpg',
  //     'https://347inmobiliaria.com/img/13/10.jpg',
  //   ],
  //   description: 'Area de Terreno 1 Hra. con arroyito de invierno en horizontal a mitad de terreno. Increíbles vistas hacia la Cordillera y el cerro Saturnino, inclusive hacia Lago Puelo. Terreno plano, con suave pendiante. Renoval de bosque nativo. No dudes en Consultar y visitarlo, te querrás hacer allí tu casita, un lugar tranquilo, rodeado de naturaleza!!!! Dentro del circuito se encuentran los accesos que te llevaran a explorar los senderos que conectan a la red de refugios de montaña más grande de Sudamérica o el acceso que conducirá al Cerro Perito Moreno, centro recreativo invernal mas importante de la zona. Dentro de la Reserva Forestal Loma del Medio - Río Azul.',
  //   price: 'USD 80.000',
  //   size: '10000',
  //   access: 'Ripio',
  //   distanceToAsphalt: '5 km',
  //   orientation: 'Oeste',
  // },
  // {
  //   id: 14,
  //   title: 'Casas',
  //   name: 'Casa Cercana Al Centro Camino A La Pasarela Y Cascada Del Motoco. Lago Puelo, Chubut',
  //   province: 'Chubut',
  //   location: 'Lago Puelo',
  //   address: 'Camino A La Pasarela Y Cascada Del Motoco. Lago Puelo',
  //   locationX: '-71.60004985158778',
  //   locationY: '-42.05017643929989',
  //   imageUrl: 'https://347inmobiliaria.com/img/14/1.jpg',
  //   images: [
  //     'https://347inmobiliaria.com/img/14/1.jpg',
  //     'https://347inmobiliaria.com/img/14/2.jpg',
  //     'https://347inmobiliaria.com/img/14/3.jpg',
  //     'https://347inmobiliaria.com/img/14/4.jpg',
  //     'https://347inmobiliaria.com/img/14/5.jpg',
  //     'https://347inmobiliaria.com/img/14/6.jpg',
  //     'https://347inmobiliaria.com/img/14/7.jpg',
  //     'https://347inmobiliaria.com/img/14/8.jpg',
  //     'https://347inmobiliaria.com/img/14/9.jpg',
  //     'https://347inmobiliaria.com/img/14/10.jpg',
  //     'https://347inmobiliaria.com/img/14/11.jpg',
  //     'https://347inmobiliaria.com/img/14/12.jpg',
  //     'https://347inmobiliaria.com/img/14/13.jpg',
  //     'https://347inmobiliaria.com/img/14/14.jpg',
  //   ],
  //   description: 'CASA en una planta, 2 dormitorios, gran jardín. Lugar de excelencia turística, IDEAL para complejo turístico, ALQUILERES de temporada, zona tranquila, con vista a las montañas. 1300m2 (dos terrenos en uno con casa en Lago Puelo). Un lugar tranquilo, residencial, maravilloso, a 7 cuadras del centro. Vas caminando al rio. Es Para no perderse esta PORTUNIDAD de visitarla e INVERTIR en un lugar que esta en pleno desarrollo!!!, Comarca Andina!!!',
  //   price: 'USD 98.000',
  //   size: '1300',
  //   build: '50',
  //   cover: '50',
  //   rooms: '3',
  //   bedrooms: '2',
  //   bathroom: '1',
  //   garage: '1',
  //   storage: '',
  //   floors: '1',
  //   orientation: 'Sur',
  //   antiquity: '10 año',
  // },
// {
  //   id: 18,
  //   title: 'Terrenos',
  //   name: 'Oportunidad!!!, Terreno En Venta De 548,18 M², Barrio Maderera, Lago Puelo',
  //   province: 'Chubut',
  //   location: 'Lago Puelo',
  //   address: 'zona del Barrio Maderera, a 300 mts del Rio Azul',
  //   locationX: '-71.5972512',
  //   locationY: '-42.0341875',
  //   imageUrl: 'https://347inmobiliaria.com/img/18/1.jpg',
  //   images: [
  //     'https://347inmobiliaria.com/img/18/1.jpg',
  //     'https://347inmobiliaria.com/img/18/2.jpg',
  //     'https://347inmobiliaria.com/img/18/3.jpg',
  //     'https://347inmobiliaria.com/img/18/4.jpg',
  //     'https://347inmobiliaria.com/img/18/5.jpg',
  //     'https://347inmobiliaria.com/img/18/6.jpg',
  //     'https://347inmobiliaria.com/img/18/7.jpg',
  //     'https://347inmobiliaria.com/img/18/8.jpg',
  //   ],
  //   description: 'EN VENTA Hermoso Terreno de 548,18 m² , arbolado en zona del Barrio Maderera, a 300 mts del Rio Azul, con preciosa vista hacia la Cordillera y el cerro Currumahuida. Zona residencial, muy tranquila. Se siente el sonido del río al descanso. LISTA para escriturar. La propiedad se encuentra a poca distancia del centro de Lago Puelo, y de atractivos turísticos como el Lago del mismo nombre, la paasarela, cascada Motoco, mirador del Río Blanco. Contactanos para visitarla!!! USD 28.000.- servicios en Puerta',
  //   price: 'USD 28.000',
  //   size: '548.18',
  //   access: 'Ripio',
  //   distanceToAsphalt: '',
  //   orientation: '',
  // },
  // {
  //   id: 27,
  //   title: 'Casas',
  //   province: 'Chubut',
  //   name: 'Casa En Lago Puelo, Amplio Jardin',
  //   location: 'Lago Puelo',
  //   address: 'Laguna Huemul',
  //   locationX: '-71.60547926406498',
  //   locationY: '-42.05197467122312',
  //   imageUrl: 'https://347inmobiliaria.com/img/27/1.jpg',
  //   images: [
  //     'https://347inmobiliaria.com/img/27/1.jpg',
  //     'https://347inmobiliaria.com/img/27/2.jpg',
  //     'https://347inmobiliaria.com/img/27/3.jpg',
  //     'https://347inmobiliaria.com/img/27/4.jpg',
  //     'https://347inmobiliaria.com/img/27/5.jpg',
  //     'https://347inmobiliaria.com/img/27/6.jpg',
  //     'https://347inmobiliaria.com/img/27/7.jpg',
  //     'https://347inmobiliaria.com/img/27/8.jpg',
  //   ],
  //   description: 'CASA con linda distribución, doble circulación.\nMuy buena ubicación en barrio residencial de Lago Puelo, isla norte, camino a la pasarela del Rio Azul, zona turística por excelencia de la comarca andina. camino de ripio.\n3 dormitorios, todos con ventanas y preciosas vistas al cerro.\nAmplio Jardín con cochera techada\njardin trasero con vistas al cerro Morrudo por un lado y el cerro Currumahuida por el otro y otra platea extra en la parte trasera de la casa.\nTodos los servicios.',
  //   price: 'USD 70.000',
  //   size: '613',
  //   build: '48',
  //   cover: '48',
  //   rooms: '4',
  //   bedrooms: '3',
  //   bathroom: '1',
  //   storage: '',
  //   garage: '',
  //   floors: '',
  //   orientation: 'Norte',
  //   antiquity: '10 años',
  // },
    // {
  //   id: 29,
  //   title: 'Casas',
  //   province: 'Chubut',
  //   name: 'Casa Tipo Chalet Isla Centro, Lago Puelo',
  //   location: 'Lago Puelo',
  //   address: 'Callejon De Pozas, Barrio 26 viviendas',
  //   locationX: '-71.60204780205906',
  //   locationY: '-42.05957694400524',
  //   imageUrl: 'https://347inmobiliaria.com/img/29/1.jpg',
  //   images: [
  //     'https://347inmobiliaria.com/img/29/1.jpg',
  //     'https://347inmobiliaria.com/img/29/2.jpg',
  //     'https://347inmobiliaria.com/img/29/3.jpg',
  //     'https://347inmobiliaria.com/img/29/4.jpg',
  //     'https://347inmobiliaria.com/img/29/5.jpg',
  //     'https://347inmobiliaria.com/img/29/6.jpg',
  //     'https://347inmobiliaria.com/img/29/7.jpg',
  //     'https://347inmobiliaria.com/img/29/8.jpg',
  //     'https://347inmobiliaria.com/img/29/9.jpg',
  //   ],
  //   description: 'Área de Terreno: 300 m2\nCASA: de 35 m2 sup cubierta\nHabitaciones: 1, Baños:1\nOrientación: sur\nDoble entrada!!!\nAltillo, tanque de agua 1.000 Lts cubierto, bomba de agua, pozo con perforacion de 8 mts. para riego. Techo de lenga, puerta de ciprés. Construccion de paredes anchas 30 cmts, antisismica y con aislación.\nCalle, barrio 26 viviendas, Lago Puelo, Chubut\nA 4 cuadras del centro de Lago Puelo,\nJardín con árboles frutales nogal, cerezo, dos limoneros, romero, laurel, notro, rosales, rododendro.\nEn la vereda tiene Arrayanes y Maitén.\nPreciosas vistas al cerro Currumahuida y al morrudo\nEscritura individual\nSERVICIOS: Agua corriente, Pozo de agua de 8 mts, luz monofásica, gas natural',
  //   price: 'USD 62.000',
  //   size: '300',
  //   build: '35',
  //   cover: '35',
  //   rooms: '2',
  //   bedrooms: '1',
  //   bathroom: '1',
  //   storage: '',
  //   garage: '',
  //   floors: '',
  //   orientation: 'Sur',
  //   antiquity: '30 años',
  // },
  // {
  //   id: 31,
  //   title: 'Terrenos',
  //   province: 'Río Negro',
  //   name: 'Terrenos Junto Al Río Azul, El Bolsón, Río Negro',
  //   location: 'El Bolsón',
  //   address: '',
  //   locationX: '-71.56520141085159',
  //   locationY: '-41.956841116426425',
  //   imageUrl: 'https://347inmobiliaria.com/img/31/1.jpg',
  //   images: [
  //     'https://347inmobiliaria.com/img/31/1.jpg',
  //     'https://347inmobiliaria.com/img/31/2.jpg',
  //   ],
  //   description: 'Terrenos en condominio con atractivos turísticos,\nque dan a la Costa del Río Azul. Rodeados de bosques con simples senderos ideal para trekking, y . El estar en la costa del Río Azul, un flujo de agua pura de deshielo que por el entorno y el cielo tanlimpio le da un color azul maravilloso y a esto debe su nombre. También se desarrolla en este río el deporte de rafting por los rápidos descensos de los ríos.\n\nTerrenos en venta:\n\nLote B: 1.947,69 m2 USD $45.000, con un frente de 40 mts y un fondo de lado izquierdo entrando 44,18 mts y del otro lado derecho\nentrando 74,91mts, fondo atras tiene 27,56 mts.\n-------------------------------------------------------------------------------------------------------------------------------------------------------------\nLote C: 1.960,36 m2 USD $45.000, con un frente de 55,19 mts, y un fondo del lado izquierdo 74,01 mts. del\nlado que comparte con el lote B, y del lado derecho 94,61 mts. , el fondo atras tiene 20,89 mts.\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------\nLote D: 4.923,80 m2 USD $80.000, con un frente de 55,19 mts y un fondo de lado izquierdo entrando 94,61 mts, que comparte con el\nLote C ; fondo del otro lado derecho 132,48 mts. y el fondo atrás tiene 40,15 mts.\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\nTienen un pilar de luz que comparten entre todos. Agua de vertiente, y está la opcion de hacer pozo de agua también\n\nPuedes comunicarte con nosotros para ir a conocerlos!!!!!!',
  //   price: 'USD 45.000',
  //   size: '1969',
  //   access: 'Tierra',
  // },



//   MODELO VACÍO
  // {
  //   id: ,
  //   title: '',
  //   province: '',
  //   name: '',
  //   location: '',
  //   address: '',
  //   locationX: '',
  //   locationY: '',
  //   imageUrl: '',
  //   images: [
  //   ],
  //   description: '',
  //   price: '',
  //   size: '',
  //   build: '',
  //   cover: '',
  //   rooms: '',
  //   bedrooms: '',
  //   bathroom: '',
  //   storage: '',
  //   garage: '',
  //   floors: '',
  //   orientation: '',
  //   antiquity: '',
  // },

];